-- MySQL Script generated by MySQL Workbench
-- 10/03/16 22:09:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CaplanTDS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CaplanTDS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CaplanTDS` DEFAULT CHARACTER SET utf8 ;
USE `CaplanTDS` ;

-- -----------------------------------------------------
-- Table `CaplanTDS`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaplanTDS`.`locations` (
  `location_id` INT NOT NULL AUTO_INCREMENT,
  `state_name` VARCHAR(20) NOT NULL,
  `county_name` VARCHAR(20) NOT NULL,
  `subcounty_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`location_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CaplanTDS`.`weeks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaplanTDS`.`weeks` (
  `week_id` INT NOT NULL AUTO_INCREMENT,
  `week_num` INT NOT NULL,
  `week_date1` DATE NOT NULL,
  `week_date2` DATE NOT NULL,
  PRIMARY KEY (`week_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CaplanTDS`.`trades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaplanTDS`.`trades` (
  `trade_id` INT NOT NULL AUTO_INCREMENT,
  `trade_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`trade_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CaplanTDS`.`LTW`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaplanTDS`.`LTW` (
  `LTW_id` INT NOT NULL AUTO_INCREMENT,
  `location_id` INT NOT NULL,
  `week_id` INT NOT NULL,
  `trade_id` INT NOT NULL,
  PRIMARY KEY (`LTW_id`),
  INDEX `location_idx` (`location_id` ASC),
  INDEX `week_idx` (`week_id` ASC),
  INDEX `trade_idx` (`trade_id` ASC),
  CONSTRAINT `location`
    FOREIGN KEY (`location_id`)
    REFERENCES `CaplanTDS`.`locations` (`location_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `week`
    FOREIGN KEY (`week_id`)
    REFERENCES `CaplanTDS`.`weeks` (`week_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `trade`
    FOREIGN KEY (`trade_id`)
    REFERENCES `CaplanTDS`.`trades` (`trade_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CaplanTDS`.`capacities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaplanTDS`.`capacities` (
  `capacity_id` INT NOT NULL AUTO_INCREMENT,
  `LTW_id` INT NOT NULL,
  `capacity_num` DECIMAL NULL,
  PRIMARY KEY (`capacity_id`),
  INDEX `LTW_idx` (`LTW_id` ASC),
  CONSTRAINT `LTW`
    FOREIGN KEY (`LTW_id`)
    REFERENCES `CaplanTDS`.`LTW` (`LTW_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CaplanTDS`.`channels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaplanTDS`.`channels` (
  `channel_id` INT NOT NULL AUTO_INCREMENT,
  `channel_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`channel_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CaplanTDS`.`forecast_actual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaplanTDS`.`forecast_actual` (
  `forecast_actual_id` INT NOT NULL AUTO_INCREMENT,
  `LTW_id` INT NOT NULL,
  `channel_id` INT NOT NULL,
  `forecast_num` DECIMAL NULL,
  `actual_num` DECIMAL NULL,
  `deviation_num` DECIMAL NULL,
  PRIMARY KEY (`forecast_actual_id`),
  INDEX `LTW2_idx` (`LTW_id` ASC),
  INDEX `channel_idx` (`channel_id` ASC),
  CONSTRAINT `LTW2`
    FOREIGN KEY (`LTW_id`)
    REFERENCES `CaplanTDS`.`LTW` (`LTW_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `channel`
    FOREIGN KEY (`channel_id`)
    REFERENCES `CaplanTDS`.`channels` (`channel_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CaplanTDS`.`types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaplanTDS`.`types` (
  `type_id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(20) NOT NULL,
  `details` VARCHAR(45) NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CaplanTDS`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CaplanTDS`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(10) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `type_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `type_idx` (`type_id` ASC),
  CONSTRAINT `type`
    FOREIGN KEY (`type_id`)
    REFERENCES `CaplanTDS`.`types` (`type_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
